<?php

namespace intranetBundle\Repository\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * channelnew_feedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class channelnew_feedRepository extends EntityRepository
{
}
