<?php

namespace intranetBundle\Repository\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * F_VacationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class F_VacationRepository extends EntityRepository
{
}
