<?php

namespace intranetBundle\Repository\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * hours_dataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hours_dataRepository extends EntityRepository
{
}
