<?php

namespace intranetBundle\Repository\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * userstasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userstasksRepository extends EntityRepository
{
}
