<?php

namespace intranetBundle\Repository\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Users_F_ExpensesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Users_F_ExpensesRepository extends EntityRepository
{
}
